name: e_library
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  file_picker: ^8.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  pdf: ^3.11.1
  pdfx: ^2.6.0

dev_dependencies: 
  #flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

